<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Extensions.CognitoAuthentication" Version="3.1.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HttpToSocks5Proxy" Version="1.4.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Data\**\*.*" />
    <None Remove="Assets\Icons\**\*.*" />
    <None Remove="Assets\Tools\**\*.*" />

    <EmbeddedResource Include="Assets\Data\**\*.*" />
    <Resource Include="Assets\Icons\**\*.*" />
    <Content Include="Assets\Tools\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="RemoveLooseDataAssetsFromOutput" BeforeTargets="CopyFilesToOutputDirectory">
    <RemoveDir
      Directories="$(TargetDir)Assets\Data"
      Condition="Exists('$(TargetDir)Assets\Data')" />
  </Target>

</Project>
